name: 'coverage'
on:
    pull_request:
        branches:
            - main
            - develop
jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      checks: write  # Grant write permission for checks API
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npm test