name: 'coverage'
on:
    pull_request:
        branches:
            - main
            - develop
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: '18'
            - run: npm ci
            - run: npm test -- --coverage --collectCoverage=true


            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                min-coverage: 50  
                coverage-file: 'coverage/coverage-final.json'
                annotations: true  
                status-badge: true 